import { NgModule } from '@angular/core';
import { FormsModule }   from '@angular/forms';
import { CommonModule } from '@angular/common';
import { DemoComponent } from './demo.component';
import { CloukitDropoutModule } from '../index';
import { CloukitStoryModule, CloukitStoryService } from '@cloukit/story';
import { Story00Component } from './stories/story-00-dropout-directions';
import { Story01Component } from './stories/story-01-off-placed-trigger-element';
import { Story02Component } from './stories/story-02-programmatic-trigger';

@NgModule({
  declarations: [
    DemoComponent,
    Story00Component,
    Story01Component,
    Story02Component,
  ],
  exports: [
    DemoComponent,
  ],
  imports: [
    CommonModule,
    FormsModule,
    CloukitStoryModule,
    CloukitDropoutModule,
  ],
  providers: [ ],
  bootstrap: [ ]
})
export class DemoModule {
  constructor(private cloukitStoryService: CloukitStoryService) {
    //
    // INITIALIZE STORY SOURCES
    //
    const baseUrl = document.getElementsByTagName('base')[0].href;
    const storySourceJsonUrl = `${baseUrl}assets/demoStoriesSource.json`; // File is auto generated by build chain!
    this.cloukitStoryService.loadStoryJson(storySourceJsonUrl);
  }
}
